### PR TITLE
Added support for sbt and scala 2.11

### PR DESCRIPTION
**Pull request by justjoheinz**
removed grade build
added support for Scala 2.11
added support for cross version builds
updated scalatest dependency
updated tests
removed unmanaged dependency to jtidy

### CODE REVIEW

**Comment by tristanjuricek** [comment]
Thank you!

I have to find where I hid my keys, and get this up on sonatype.

**Comment by eed3si9n** [comment]
+1 on Scala 2.11 builds. Looking forward to a release on this.

**Comment by tristanjuricek** [comment]
I've seemed to run into some kind of issue with sonatype, I've opened up a ticket, so, this should be up once that's resolved.

**Comment by justjoheinz** [comment]
I just saw that there are other branches as well with sbt support, which I had not seen. You might want to set at least the organization in the sbt file. Once it is published I could make a small play-markdown template interpreter (via twirl) available.

**Comment by tristanjuricek** [comment]
OK, I missed something simple, and the 2.10 and 2.11 releases should be available now.

**Pull request merged**
